[2024-02-18T20:31:52.047+0000] {processor.py:161} INFO - Started process (PID=3812) to work on /opt/airflow/dags/ETL_LichtBlick.py
[2024-02-18T20:31:52.056+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/ETL_LichtBlick.py for tasks to queue
[2024-02-18T20:31:52.060+0000] {logging_mixin.py:188} INFO - [2024-02-18T20:31:52.059+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/ETL_LichtBlick.py
[2024-02-18T20:31:55.125+0000] {logging_mixin.py:188} INFO - [2024-02-18T20:31:55.122+0000] {templater.py:95} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/template/templater.py", line 93, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/airflow/.local/lib/python3.8/site-packages/jinja2/loaders.py", line 204, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: ./dags/script/Dim.sql
[2024-02-18T20:31:55.128+0000] {logging_mixin.py:188} INFO - [2024-02-18T20:31:55.127+0000] {templater.py:95} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/template/templater.py", line 93, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/airflow/.local/lib/python3.8/site-packages/jinja2/loaders.py", line 204, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: ./dags/script/Dim.sql
[2024-02-18T20:31:55.138+0000] {processor.py:840} INFO - DAG(s) 'csv_to_sqlserver_dag' retrieved from /opt/airflow/dags/ETL_LichtBlick.py
[2024-02-18T20:31:55.211+0000] {logging_mixin.py:188} INFO - [2024-02-18T20:31:55.210+0000] {dag.py:3036} INFO - Sync 1 DAGs
[2024-02-18T20:31:55.238+0000] {logging_mixin.py:188} INFO - [2024-02-18T20:31:55.238+0000] {dag.py:3823} INFO - Setting next_dagrun for csv_to_sqlserver_dag to None, run_after=None
[2024-02-18T20:31:55.273+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/ETL_LichtBlick.py took 3.241 seconds
[2024-02-18T20:37:52.063+0000] {processor.py:161} INFO - Started process (PID=3954) to work on /opt/airflow/dags/ETL_LichtBlick.py
[2024-02-18T20:37:52.065+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/ETL_LichtBlick.py for tasks to queue
[2024-02-18T20:37:52.067+0000] {logging_mixin.py:188} INFO - [2024-02-18T20:37:52.066+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/ETL_LichtBlick.py
[2024-02-18T20:37:53.475+0000] {logging_mixin.py:188} INFO - [2024-02-18T20:37:53.473+0000] {templater.py:95} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/template/templater.py", line 93, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/airflow/.local/lib/python3.8/site-packages/jinja2/loaders.py", line 204, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: ./dags/script/Dim.sql
[2024-02-18T20:37:53.478+0000] {logging_mixin.py:188} INFO - [2024-02-18T20:37:53.477+0000] {templater.py:95} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/template/templater.py", line 93, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/airflow/.local/lib/python3.8/site-packages/jinja2/loaders.py", line 204, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: ./dags/script/Dim.sql
[2024-02-18T20:37:53.485+0000] {processor.py:840} INFO - DAG(s) 'csv_to_sqlserver_dag' retrieved from /opt/airflow/dags/ETL_LichtBlick.py
[2024-02-18T20:37:53.528+0000] {logging_mixin.py:188} INFO - [2024-02-18T20:37:53.527+0000] {dag.py:3036} INFO - Sync 1 DAGs
[2024-02-18T20:37:53.546+0000] {logging_mixin.py:188} INFO - [2024-02-18T20:37:53.545+0000] {dag.py:3823} INFO - Setting next_dagrun for csv_to_sqlserver_dag to None, run_after=None
[2024-02-18T20:37:53.595+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/ETL_LichtBlick.py took 1.539 seconds
[2024-02-18T20:38:23.952+0000] {processor.py:161} INFO - Started process (PID=3966) to work on /opt/airflow/dags/ETL_LichtBlick.py
[2024-02-18T20:38:23.954+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/ETL_LichtBlick.py for tasks to queue
[2024-02-18T20:38:23.956+0000] {logging_mixin.py:188} INFO - [2024-02-18T20:38:23.955+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/ETL_LichtBlick.py
[2024-02-18T20:38:25.227+0000] {logging_mixin.py:188} INFO - [2024-02-18T20:38:25.225+0000] {templater.py:95} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/template/templater.py", line 93, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/airflow/.local/lib/python3.8/site-packages/jinja2/loaders.py", line 204, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: ./dags/script/Dim.sql
[2024-02-18T20:38:25.230+0000] {logging_mixin.py:188} INFO - [2024-02-18T20:38:25.229+0000] {templater.py:95} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/template/templater.py", line 93, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/airflow/.local/lib/python3.8/site-packages/jinja2/loaders.py", line 204, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: ./dags/script/Dim.sql
[2024-02-18T20:38:25.240+0000] {processor.py:840} INFO - DAG(s) 'csv_to_sqlserver_dag' retrieved from /opt/airflow/dags/ETL_LichtBlick.py
[2024-02-18T20:38:25.328+0000] {logging_mixin.py:188} INFO - [2024-02-18T20:38:25.320+0000] {dag.py:3036} INFO - Sync 1 DAGs
[2024-02-18T20:38:25.391+0000] {logging_mixin.py:188} INFO - [2024-02-18T20:38:25.390+0000] {dag.py:3823} INFO - Setting next_dagrun for csv_to_sqlserver_dag to None, run_after=None
[2024-02-18T20:38:25.528+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/ETL_LichtBlick.py took 1.581 seconds
[2024-02-18T20:38:56.555+0000] {processor.py:161} INFO - Started process (PID=3978) to work on /opt/airflow/dags/ETL_LichtBlick.py
[2024-02-18T20:38:56.634+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/ETL_LichtBlick.py for tasks to queue
[2024-02-18T20:38:56.700+0000] {logging_mixin.py:188} INFO - [2024-02-18T20:38:56.699+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/ETL_LichtBlick.py
[2024-02-18T20:39:00.843+0000] {logging_mixin.py:188} INFO - [2024-02-18T20:39:00.835+0000] {templater.py:95} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/template/templater.py", line 93, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/airflow/.local/lib/python3.8/site-packages/jinja2/loaders.py", line 204, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: ./dags/script/Dim.sql
[2024-02-18T20:39:00.851+0000] {logging_mixin.py:188} INFO - [2024-02-18T20:39:00.848+0000] {templater.py:95} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/template/templater.py", line 93, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/airflow/.local/lib/python3.8/site-packages/jinja2/loaders.py", line 204, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: ./dags/script/Dim.sql
[2024-02-18T20:39:00.922+0000] {processor.py:840} INFO - DAG(s) 'csv_to_sqlserver_dag' retrieved from /opt/airflow/dags/ETL_LichtBlick.py
[2024-02-18T20:39:01.124+0000] {logging_mixin.py:188} INFO - [2024-02-18T20:39:01.120+0000] {dag.py:3036} INFO - Sync 1 DAGs
[2024-02-18T20:39:01.167+0000] {logging_mixin.py:188} INFO - [2024-02-18T20:39:01.167+0000] {dag.py:3823} INFO - Setting next_dagrun for csv_to_sqlserver_dag to None, run_after=None
[2024-02-18T20:39:01.258+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/ETL_LichtBlick.py took 4.732 seconds
[2024-02-18T20:39:32.166+0000] {processor.py:161} INFO - Started process (PID=3997) to work on /opt/airflow/dags/ETL_LichtBlick.py
[2024-02-18T20:39:32.169+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/ETL_LichtBlick.py for tasks to queue
[2024-02-18T20:39:32.172+0000] {logging_mixin.py:188} INFO - [2024-02-18T20:39:32.172+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/ETL_LichtBlick.py
[2024-02-18T20:39:34.277+0000] {logging_mixin.py:188} INFO - [2024-02-18T20:39:34.266+0000] {templater.py:95} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/template/templater.py", line 93, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/airflow/.local/lib/python3.8/site-packages/jinja2/loaders.py", line 204, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: ./dags/script/Dim.sql
[2024-02-18T20:39:34.281+0000] {logging_mixin.py:188} INFO - [2024-02-18T20:39:34.281+0000] {templater.py:95} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/template/templater.py", line 93, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/airflow/.local/lib/python3.8/site-packages/jinja2/loaders.py", line 204, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: ./dags/script/Dim.sql
[2024-02-18T20:39:34.314+0000] {processor.py:840} INFO - DAG(s) 'csv_to_sqlserver_dag' retrieved from /opt/airflow/dags/ETL_LichtBlick.py
[2024-02-18T20:39:34.781+0000] {logging_mixin.py:188} INFO - [2024-02-18T20:39:34.769+0000] {dag.py:3036} INFO - Sync 1 DAGs
[2024-02-18T20:39:34.835+0000] {logging_mixin.py:188} INFO - [2024-02-18T20:39:34.835+0000] {dag.py:3823} INFO - Setting next_dagrun for csv_to_sqlserver_dag to None, run_after=None
[2024-02-18T20:39:34.914+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/ETL_LichtBlick.py took 2.759 seconds
[2024-02-18T20:40:05.810+0000] {processor.py:161} INFO - Started process (PID=4009) to work on /opt/airflow/dags/ETL_LichtBlick.py
[2024-02-18T20:40:05.813+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/ETL_LichtBlick.py for tasks to queue
[2024-02-18T20:40:05.818+0000] {logging_mixin.py:188} INFO - [2024-02-18T20:40:05.817+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/ETL_LichtBlick.py
[2024-02-18T20:40:08.660+0000] {logging_mixin.py:188} INFO - [2024-02-18T20:40:08.653+0000] {templater.py:95} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/template/templater.py", line 93, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/airflow/.local/lib/python3.8/site-packages/jinja2/loaders.py", line 204, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: ./dags/script/Dim.sql
[2024-02-18T20:40:08.663+0000] {logging_mixin.py:188} INFO - [2024-02-18T20:40:08.663+0000] {templater.py:95} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/template/templater.py", line 93, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/airflow/.local/lib/python3.8/site-packages/jinja2/loaders.py", line 204, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: ./dags/script/Dim.sql
[2024-02-18T20:40:08.676+0000] {processor.py:840} INFO - DAG(s) 'csv_to_sqlserver_dag' retrieved from /opt/airflow/dags/ETL_LichtBlick.py
[2024-02-18T20:40:08.738+0000] {logging_mixin.py:188} INFO - [2024-02-18T20:40:08.736+0000] {dag.py:3036} INFO - Sync 1 DAGs
[2024-02-18T20:40:08.764+0000] {logging_mixin.py:188} INFO - [2024-02-18T20:40:08.763+0000] {dag.py:3823} INFO - Setting next_dagrun for csv_to_sqlserver_dag to None, run_after=None
[2024-02-18T20:40:08.803+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/ETL_LichtBlick.py took 3.001 seconds
[2024-02-18T20:40:39.172+0000] {processor.py:161} INFO - Started process (PID=4021) to work on /opt/airflow/dags/ETL_LichtBlick.py
[2024-02-18T20:40:39.174+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/ETL_LichtBlick.py for tasks to queue
[2024-02-18T20:40:39.178+0000] {logging_mixin.py:188} INFO - [2024-02-18T20:40:39.177+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/ETL_LichtBlick.py
[2024-02-18T20:40:40.331+0000] {logging_mixin.py:188} INFO - [2024-02-18T20:40:40.330+0000] {templater.py:95} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/template/templater.py", line 93, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/airflow/.local/lib/python3.8/site-packages/jinja2/loaders.py", line 204, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: ./dags/script/Dim.sql
[2024-02-18T20:40:40.333+0000] {logging_mixin.py:188} INFO - [2024-02-18T20:40:40.333+0000] {templater.py:95} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/template/templater.py", line 93, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/airflow/.local/lib/python3.8/site-packages/jinja2/loaders.py", line 204, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: ./dags/script/Dim.sql
[2024-02-18T20:40:40.338+0000] {processor.py:840} INFO - DAG(s) 'csv_to_sqlserver_dag' retrieved from /opt/airflow/dags/ETL_LichtBlick.py
[2024-02-18T20:40:40.379+0000] {logging_mixin.py:188} INFO - [2024-02-18T20:40:40.378+0000] {dag.py:3036} INFO - Sync 1 DAGs
[2024-02-18T20:40:40.397+0000] {logging_mixin.py:188} INFO - [2024-02-18T20:40:40.396+0000] {dag.py:3823} INFO - Setting next_dagrun for csv_to_sqlserver_dag to None, run_after=None
[2024-02-18T20:40:40.429+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/ETL_LichtBlick.py took 1.263 seconds
[2024-02-18T20:41:10.539+0000] {processor.py:161} INFO - Started process (PID=4033) to work on /opt/airflow/dags/ETL_LichtBlick.py
[2024-02-18T20:41:10.540+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/ETL_LichtBlick.py for tasks to queue
[2024-02-18T20:41:10.542+0000] {logging_mixin.py:188} INFO - [2024-02-18T20:41:10.542+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/ETL_LichtBlick.py
[2024-02-18T20:41:11.663+0000] {logging_mixin.py:188} INFO - [2024-02-18T20:41:11.654+0000] {templater.py:95} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/template/templater.py", line 93, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/airflow/.local/lib/python3.8/site-packages/jinja2/loaders.py", line 204, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: ./dags/script/Dim.sql
[2024-02-18T20:41:11.666+0000] {logging_mixin.py:188} INFO - [2024-02-18T20:41:11.665+0000] {templater.py:95} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/template/templater.py", line 93, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/airflow/.local/lib/python3.8/site-packages/jinja2/loaders.py", line 204, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: ./dags/script/Dim.sql
[2024-02-18T20:41:11.672+0000] {processor.py:840} INFO - DAG(s) 'csv_to_sqlserver_dag' retrieved from /opt/airflow/dags/ETL_LichtBlick.py
[2024-02-18T20:41:11.711+0000] {logging_mixin.py:188} INFO - [2024-02-18T20:41:11.711+0000] {dag.py:3036} INFO - Sync 1 DAGs
[2024-02-18T20:41:11.728+0000] {logging_mixin.py:188} INFO - [2024-02-18T20:41:11.727+0000] {dag.py:3823} INFO - Setting next_dagrun for csv_to_sqlserver_dag to None, run_after=None
[2024-02-18T20:41:11.759+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/ETL_LichtBlick.py took 1.226 seconds
[2024-02-18T20:41:42.197+0000] {processor.py:161} INFO - Started process (PID=4045) to work on /opt/airflow/dags/ETL_LichtBlick.py
[2024-02-18T20:41:42.199+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/ETL_LichtBlick.py for tasks to queue
[2024-02-18T20:41:42.201+0000] {logging_mixin.py:188} INFO - [2024-02-18T20:41:42.201+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/ETL_LichtBlick.py
[2024-02-18T20:41:43.516+0000] {logging_mixin.py:188} INFO - [2024-02-18T20:41:43.510+0000] {templater.py:95} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/template/templater.py", line 93, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/airflow/.local/lib/python3.8/site-packages/jinja2/loaders.py", line 204, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: ./dags/script/Dim.sql
[2024-02-18T20:41:43.520+0000] {logging_mixin.py:188} INFO - [2024-02-18T20:41:43.519+0000] {templater.py:95} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/template/templater.py", line 93, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/airflow/.local/lib/python3.8/site-packages/jinja2/loaders.py", line 204, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: ./dags/script/Dim.sql
[2024-02-18T20:41:43.525+0000] {processor.py:840} INFO - DAG(s) 'csv_to_sqlserver_dag' retrieved from /opt/airflow/dags/ETL_LichtBlick.py
[2024-02-18T20:41:43.581+0000] {logging_mixin.py:188} INFO - [2024-02-18T20:41:43.581+0000] {dag.py:3036} INFO - Sync 1 DAGs
[2024-02-18T20:41:43.598+0000] {logging_mixin.py:188} INFO - [2024-02-18T20:41:43.597+0000] {dag.py:3823} INFO - Setting next_dagrun for csv_to_sqlserver_dag to None, run_after=None
[2024-02-18T20:41:43.633+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/ETL_LichtBlick.py took 1.442 seconds
[2024-02-18T20:42:14.047+0000] {processor.py:161} INFO - Started process (PID=4057) to work on /opt/airflow/dags/ETL_LichtBlick.py
[2024-02-18T20:42:14.053+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/ETL_LichtBlick.py for tasks to queue
[2024-02-18T20:42:14.055+0000] {logging_mixin.py:188} INFO - [2024-02-18T20:42:14.054+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/ETL_LichtBlick.py
[2024-02-18T20:42:15.074+0000] {logging_mixin.py:188} INFO - [2024-02-18T20:42:15.066+0000] {templater.py:95} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/template/templater.py", line 93, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/airflow/.local/lib/python3.8/site-packages/jinja2/loaders.py", line 204, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: ./dags/script/Dim.sql
[2024-02-18T20:42:15.077+0000] {logging_mixin.py:188} INFO - [2024-02-18T20:42:15.076+0000] {templater.py:95} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/template/templater.py", line 93, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/airflow/.local/lib/python3.8/site-packages/jinja2/loaders.py", line 204, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: ./dags/script/Dim.sql
[2024-02-18T20:42:15.082+0000] {processor.py:840} INFO - DAG(s) 'csv_to_sqlserver_dag' retrieved from /opt/airflow/dags/ETL_LichtBlick.py
[2024-02-18T20:42:15.121+0000] {logging_mixin.py:188} INFO - [2024-02-18T20:42:15.120+0000] {dag.py:3036} INFO - Sync 1 DAGs
[2024-02-18T20:42:15.141+0000] {logging_mixin.py:188} INFO - [2024-02-18T20:42:15.141+0000] {dag.py:3823} INFO - Setting next_dagrun for csv_to_sqlserver_dag to None, run_after=None
[2024-02-18T20:42:15.175+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/ETL_LichtBlick.py took 1.134 seconds
[2024-02-18T20:42:45.829+0000] {processor.py:161} INFO - Started process (PID=4069) to work on /opt/airflow/dags/ETL_LichtBlick.py
[2024-02-18T20:42:45.833+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/ETL_LichtBlick.py for tasks to queue
[2024-02-18T20:42:45.845+0000] {logging_mixin.py:188} INFO - [2024-02-18T20:42:45.843+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/ETL_LichtBlick.py
[2024-02-18T20:42:49.423+0000] {logging_mixin.py:188} INFO - [2024-02-18T20:42:49.408+0000] {templater.py:95} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/template/templater.py", line 93, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/airflow/.local/lib/python3.8/site-packages/jinja2/loaders.py", line 204, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: ./dags/script/Dim.sql
[2024-02-18T20:42:49.426+0000] {logging_mixin.py:188} INFO - [2024-02-18T20:42:49.425+0000] {templater.py:95} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/template/templater.py", line 93, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/airflow/.local/lib/python3.8/site-packages/jinja2/loaders.py", line 204, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: ./dags/script/Dim.sql
[2024-02-18T20:42:49.444+0000] {processor.py:840} INFO - DAG(s) 'csv_to_sqlserver_dag' retrieved from /opt/airflow/dags/ETL_LichtBlick.py
[2024-02-18T20:42:49.719+0000] {logging_mixin.py:188} INFO - [2024-02-18T20:42:49.717+0000] {dag.py:3036} INFO - Sync 1 DAGs
[2024-02-18T20:42:49.885+0000] {logging_mixin.py:188} INFO - [2024-02-18T20:42:49.884+0000] {dag.py:3823} INFO - Setting next_dagrun for csv_to_sqlserver_dag to None, run_after=None
[2024-02-18T20:42:50.095+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/ETL_LichtBlick.py took 4.233 seconds
[2024-02-18T20:43:20.353+0000] {processor.py:161} INFO - Started process (PID=4081) to work on /opt/airflow/dags/ETL_LichtBlick.py
[2024-02-18T20:43:20.357+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/ETL_LichtBlick.py for tasks to queue
[2024-02-18T20:43:20.360+0000] {logging_mixin.py:188} INFO - [2024-02-18T20:43:20.359+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/ETL_LichtBlick.py
[2024-02-18T20:43:21.446+0000] {logging_mixin.py:188} INFO - [2024-02-18T20:43:21.444+0000] {templater.py:95} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/template/templater.py", line 93, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/airflow/.local/lib/python3.8/site-packages/jinja2/loaders.py", line 204, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: ./dags/script/Dim.sql
[2024-02-18T20:43:21.448+0000] {logging_mixin.py:188} INFO - [2024-02-18T20:43:21.447+0000] {templater.py:95} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/template/templater.py", line 93, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/airflow/.local/lib/python3.8/site-packages/jinja2/loaders.py", line 204, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: ./dags/script/Dim.sql
[2024-02-18T20:43:21.453+0000] {processor.py:840} INFO - DAG(s) 'csv_to_sqlserver_dag' retrieved from /opt/airflow/dags/ETL_LichtBlick.py
[2024-02-18T20:43:21.494+0000] {logging_mixin.py:188} INFO - [2024-02-18T20:43:21.493+0000] {dag.py:3036} INFO - Sync 1 DAGs
[2024-02-18T20:43:21.516+0000] {logging_mixin.py:188} INFO - [2024-02-18T20:43:21.516+0000] {dag.py:3823} INFO - Setting next_dagrun for csv_to_sqlserver_dag to None, run_after=None
[2024-02-18T20:43:21.554+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/ETL_LichtBlick.py took 1.209 seconds
[2024-02-18T20:43:51.826+0000] {processor.py:161} INFO - Started process (PID=4093) to work on /opt/airflow/dags/ETL_LichtBlick.py
[2024-02-18T20:43:51.831+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/ETL_LichtBlick.py for tasks to queue
[2024-02-18T20:43:51.833+0000] {logging_mixin.py:188} INFO - [2024-02-18T20:43:51.832+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/ETL_LichtBlick.py
[2024-02-18T20:43:53.396+0000] {logging_mixin.py:188} INFO - [2024-02-18T20:43:53.374+0000] {templater.py:95} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/template/templater.py", line 93, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/airflow/.local/lib/python3.8/site-packages/jinja2/loaders.py", line 204, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: ./dags/script/Dim.sql
[2024-02-18T20:43:53.398+0000] {logging_mixin.py:188} INFO - [2024-02-18T20:43:53.398+0000] {templater.py:95} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/template/templater.py", line 93, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/airflow/.local/lib/python3.8/site-packages/jinja2/loaders.py", line 204, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: ./dags/script/Dim.sql
[2024-02-18T20:43:53.445+0000] {processor.py:840} INFO - DAG(s) 'csv_to_sqlserver_dag' retrieved from /opt/airflow/dags/ETL_LichtBlick.py
[2024-02-18T20:43:53.533+0000] {logging_mixin.py:188} INFO - [2024-02-18T20:43:53.532+0000] {dag.py:3036} INFO - Sync 1 DAGs
[2024-02-18T20:43:53.576+0000] {logging_mixin.py:188} INFO - [2024-02-18T20:43:53.567+0000] {dag.py:3823} INFO - Setting next_dagrun for csv_to_sqlserver_dag to None, run_after=None
[2024-02-18T20:43:53.679+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/ETL_LichtBlick.py took 1.859 seconds
[2024-02-18T20:44:24.284+0000] {processor.py:161} INFO - Started process (PID=4105) to work on /opt/airflow/dags/ETL_LichtBlick.py
[2024-02-18T20:44:24.287+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/ETL_LichtBlick.py for tasks to queue
[2024-02-18T20:44:24.290+0000] {logging_mixin.py:188} INFO - [2024-02-18T20:44:24.289+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/ETL_LichtBlick.py
[2024-02-18T20:44:25.426+0000] {logging_mixin.py:188} INFO - [2024-02-18T20:44:25.424+0000] {templater.py:95} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/template/templater.py", line 93, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/airflow/.local/lib/python3.8/site-packages/jinja2/loaders.py", line 204, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: ./dags/script/Dim.sql
[2024-02-18T20:44:25.428+0000] {logging_mixin.py:188} INFO - [2024-02-18T20:44:25.427+0000] {templater.py:95} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/template/templater.py", line 93, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/airflow/.local/lib/python3.8/site-packages/jinja2/loaders.py", line 204, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: ./dags/script/Dim.sql
[2024-02-18T20:44:25.434+0000] {processor.py:840} INFO - DAG(s) 'csv_to_sqlserver_dag' retrieved from /opt/airflow/dags/ETL_LichtBlick.py
[2024-02-18T20:44:25.481+0000] {logging_mixin.py:188} INFO - [2024-02-18T20:44:25.480+0000] {dag.py:3036} INFO - Sync 1 DAGs
[2024-02-18T20:44:25.499+0000] {logging_mixin.py:188} INFO - [2024-02-18T20:44:25.498+0000] {dag.py:3823} INFO - Setting next_dagrun for csv_to_sqlserver_dag to None, run_after=None
[2024-02-18T20:44:25.530+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/ETL_LichtBlick.py took 1.263 seconds
[2024-02-18T20:44:55.923+0000] {processor.py:161} INFO - Started process (PID=4117) to work on /opt/airflow/dags/ETL_LichtBlick.py
[2024-02-18T20:44:55.926+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/ETL_LichtBlick.py for tasks to queue
[2024-02-18T20:44:55.928+0000] {logging_mixin.py:188} INFO - [2024-02-18T20:44:55.928+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/ETL_LichtBlick.py
[2024-02-18T20:44:57.702+0000] {logging_mixin.py:188} INFO - [2024-02-18T20:44:57.692+0000] {templater.py:95} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/template/templater.py", line 93, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/airflow/.local/lib/python3.8/site-packages/jinja2/loaders.py", line 204, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: ./dags/script/Dim.sql
[2024-02-18T20:44:57.704+0000] {logging_mixin.py:188} INFO - [2024-02-18T20:44:57.703+0000] {templater.py:95} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/template/templater.py", line 93, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/airflow/.local/lib/python3.8/site-packages/jinja2/loaders.py", line 204, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: ./dags/script/Dim.sql
[2024-02-18T20:44:57.715+0000] {processor.py:840} INFO - DAG(s) 'csv_to_sqlserver_dag' retrieved from /opt/airflow/dags/ETL_LichtBlick.py
[2024-02-18T20:44:57.767+0000] {logging_mixin.py:188} INFO - [2024-02-18T20:44:57.766+0000] {dag.py:3036} INFO - Sync 1 DAGs
[2024-02-18T20:44:57.783+0000] {logging_mixin.py:188} INFO - [2024-02-18T20:44:57.783+0000] {dag.py:3823} INFO - Setting next_dagrun for csv_to_sqlserver_dag to None, run_after=None
[2024-02-18T20:44:57.860+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/ETL_LichtBlick.py took 1.947 seconds
[2024-02-18T20:45:28.039+0000] {processor.py:161} INFO - Started process (PID=4129) to work on /opt/airflow/dags/ETL_LichtBlick.py
[2024-02-18T20:45:28.041+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/ETL_LichtBlick.py for tasks to queue
[2024-02-18T20:45:28.043+0000] {logging_mixin.py:188} INFO - [2024-02-18T20:45:28.043+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/ETL_LichtBlick.py
[2024-02-18T20:45:29.149+0000] {logging_mixin.py:188} INFO - [2024-02-18T20:45:29.144+0000] {templater.py:95} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/template/templater.py", line 93, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/airflow/.local/lib/python3.8/site-packages/jinja2/loaders.py", line 204, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: ./dags/script/Dim.sql
[2024-02-18T20:45:29.152+0000] {logging_mixin.py:188} INFO - [2024-02-18T20:45:29.151+0000] {templater.py:95} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/template/templater.py", line 93, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/airflow/.local/lib/python3.8/site-packages/jinja2/loaders.py", line 204, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: ./dags/script/Dim.sql
[2024-02-18T20:45:29.162+0000] {processor.py:840} INFO - DAG(s) 'csv_to_sqlserver_dag' retrieved from /opt/airflow/dags/ETL_LichtBlick.py
[2024-02-18T20:45:29.204+0000] {logging_mixin.py:188} INFO - [2024-02-18T20:45:29.203+0000] {dag.py:3036} INFO - Sync 1 DAGs
[2024-02-18T20:45:29.223+0000] {logging_mixin.py:188} INFO - [2024-02-18T20:45:29.223+0000] {dag.py:3823} INFO - Setting next_dagrun for csv_to_sqlserver_dag to None, run_after=None
[2024-02-18T20:45:29.254+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/ETL_LichtBlick.py took 1.224 seconds
[2024-02-18T20:45:59.556+0000] {processor.py:161} INFO - Started process (PID=4141) to work on /opt/airflow/dags/ETL_LichtBlick.py
[2024-02-18T20:45:59.562+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/ETL_LichtBlick.py for tasks to queue
[2024-02-18T20:45:59.565+0000] {logging_mixin.py:188} INFO - [2024-02-18T20:45:59.564+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/ETL_LichtBlick.py
[2024-02-18T20:46:01.117+0000] {logging_mixin.py:188} INFO - [2024-02-18T20:46:01.115+0000] {templater.py:95} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/template/templater.py", line 93, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/airflow/.local/lib/python3.8/site-packages/jinja2/loaders.py", line 204, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: ./dags/script/Dim.sql
[2024-02-18T20:46:01.120+0000] {logging_mixin.py:188} INFO - [2024-02-18T20:46:01.119+0000] {templater.py:95} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/template/templater.py", line 93, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/airflow/.local/lib/python3.8/site-packages/jinja2/loaders.py", line 204, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: ./dags/script/Dim.sql
[2024-02-18T20:46:01.136+0000] {processor.py:840} INFO - DAG(s) 'csv_to_sqlserver_dag' retrieved from /opt/airflow/dags/ETL_LichtBlick.py
[2024-02-18T20:46:01.251+0000] {logging_mixin.py:188} INFO - [2024-02-18T20:46:01.249+0000] {dag.py:3036} INFO - Sync 1 DAGs
[2024-02-18T20:46:01.271+0000] {logging_mixin.py:188} INFO - [2024-02-18T20:46:01.271+0000] {dag.py:3823} INFO - Setting next_dagrun for csv_to_sqlserver_dag to None, run_after=None
[2024-02-18T20:46:01.324+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/ETL_LichtBlick.py took 1.778 seconds
[2024-02-18T20:46:31.861+0000] {processor.py:161} INFO - Started process (PID=4159) to work on /opt/airflow/dags/ETL_LichtBlick.py
[2024-02-18T20:46:31.863+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/ETL_LichtBlick.py for tasks to queue
[2024-02-18T20:46:31.865+0000] {logging_mixin.py:188} INFO - [2024-02-18T20:46:31.864+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/ETL_LichtBlick.py
[2024-02-18T20:46:33.025+0000] {logging_mixin.py:188} INFO - [2024-02-18T20:46:33.023+0000] {templater.py:95} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/template/templater.py", line 93, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/airflow/.local/lib/python3.8/site-packages/jinja2/loaders.py", line 204, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: ./dags/script/Dim.sql
[2024-02-18T20:46:33.028+0000] {logging_mixin.py:188} INFO - [2024-02-18T20:46:33.027+0000] {templater.py:95} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/template/templater.py", line 93, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/airflow/.local/lib/python3.8/site-packages/jinja2/loaders.py", line 204, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: ./dags/script/Dim.sql
[2024-02-18T20:46:33.039+0000] {processor.py:840} INFO - DAG(s) 'csv_to_sqlserver_dag' retrieved from /opt/airflow/dags/ETL_LichtBlick.py
[2024-02-18T20:46:33.113+0000] {logging_mixin.py:188} INFO - [2024-02-18T20:46:33.112+0000] {dag.py:3036} INFO - Sync 1 DAGs
[2024-02-18T20:46:33.133+0000] {logging_mixin.py:188} INFO - [2024-02-18T20:46:33.132+0000] {dag.py:3823} INFO - Setting next_dagrun for csv_to_sqlserver_dag to None, run_after=None
[2024-02-18T20:46:33.174+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/ETL_LichtBlick.py took 1.319 seconds
[2024-02-18T20:47:03.397+0000] {processor.py:161} INFO - Started process (PID=4171) to work on /opt/airflow/dags/ETL_LichtBlick.py
[2024-02-18T20:47:03.399+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/ETL_LichtBlick.py for tasks to queue
[2024-02-18T20:47:03.401+0000] {logging_mixin.py:188} INFO - [2024-02-18T20:47:03.400+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/ETL_LichtBlick.py
[2024-02-18T20:47:04.607+0000] {logging_mixin.py:188} INFO - [2024-02-18T20:47:04.601+0000] {templater.py:95} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/template/templater.py", line 93, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/airflow/.local/lib/python3.8/site-packages/jinja2/loaders.py", line 204, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: ./dags/script/Dim.sql
[2024-02-18T20:47:04.611+0000] {logging_mixin.py:188} INFO - [2024-02-18T20:47:04.610+0000] {templater.py:95} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/template/templater.py", line 93, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/airflow/.local/lib/python3.8/site-packages/jinja2/loaders.py", line 204, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: ./dags/script/Dim.sql
[2024-02-18T20:47:04.641+0000] {processor.py:840} INFO - DAG(s) 'csv_to_sqlserver_dag' retrieved from /opt/airflow/dags/ETL_LichtBlick.py
[2024-02-18T20:47:04.814+0000] {logging_mixin.py:188} INFO - [2024-02-18T20:47:04.813+0000] {dag.py:3036} INFO - Sync 1 DAGs
[2024-02-18T20:47:04.898+0000] {logging_mixin.py:188} INFO - [2024-02-18T20:47:04.897+0000] {dag.py:3823} INFO - Setting next_dagrun for csv_to_sqlserver_dag to None, run_after=None
[2024-02-18T20:47:04.950+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/ETL_LichtBlick.py took 1.562 seconds
[2024-02-18T20:47:35.809+0000] {processor.py:161} INFO - Started process (PID=4184) to work on /opt/airflow/dags/ETL_LichtBlick.py
[2024-02-18T20:47:35.812+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/ETL_LichtBlick.py for tasks to queue
[2024-02-18T20:47:35.815+0000] {logging_mixin.py:188} INFO - [2024-02-18T20:47:35.814+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/ETL_LichtBlick.py
[2024-02-18T20:47:37.386+0000] {logging_mixin.py:188} INFO - [2024-02-18T20:47:37.379+0000] {templater.py:95} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/template/templater.py", line 93, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/airflow/.local/lib/python3.8/site-packages/jinja2/loaders.py", line 204, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: ./dags/script/Dim.sql
[2024-02-18T20:47:37.412+0000] {logging_mixin.py:188} INFO - [2024-02-18T20:47:37.411+0000] {templater.py:95} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/template/templater.py", line 93, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/airflow/.local/lib/python3.8/site-packages/jinja2/loaders.py", line 204, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: ./dags/script/Dim.sql
[2024-02-18T20:47:37.434+0000] {processor.py:840} INFO - DAG(s) 'csv_to_sqlserver_dag' retrieved from /opt/airflow/dags/ETL_LichtBlick.py
[2024-02-18T20:47:37.540+0000] {logging_mixin.py:188} INFO - [2024-02-18T20:47:37.539+0000] {dag.py:3036} INFO - Sync 1 DAGs
[2024-02-18T20:47:37.561+0000] {logging_mixin.py:188} INFO - [2024-02-18T20:47:37.561+0000] {dag.py:3823} INFO - Setting next_dagrun for csv_to_sqlserver_dag to None, run_after=None
[2024-02-18T20:47:37.604+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/ETL_LichtBlick.py took 1.813 seconds
[2024-02-18T20:48:08.367+0000] {processor.py:161} INFO - Started process (PID=4196) to work on /opt/airflow/dags/ETL_LichtBlick.py
[2024-02-18T20:48:08.378+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/ETL_LichtBlick.py for tasks to queue
[2024-02-18T20:48:08.385+0000] {logging_mixin.py:188} INFO - [2024-02-18T20:48:08.384+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/ETL_LichtBlick.py
[2024-02-18T20:48:12.701+0000] {logging_mixin.py:188} INFO - [2024-02-18T20:48:12.673+0000] {templater.py:95} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/template/templater.py", line 93, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/airflow/.local/lib/python3.8/site-packages/jinja2/loaders.py", line 204, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: ./dags/script/Dim.sql
[2024-02-18T20:48:12.711+0000] {logging_mixin.py:188} INFO - [2024-02-18T20:48:12.711+0000] {templater.py:95} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/template/templater.py", line 93, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/airflow/.local/lib/python3.8/site-packages/jinja2/loaders.py", line 204, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: ./dags/script/Dim.sql
[2024-02-18T20:48:12.763+0000] {processor.py:840} INFO - DAG(s) 'csv_to_sqlserver_dag' retrieved from /opt/airflow/dags/ETL_LichtBlick.py
[2024-02-18T20:48:12.911+0000] {logging_mixin.py:188} INFO - [2024-02-18T20:48:12.899+0000] {dag.py:3036} INFO - Sync 1 DAGs
[2024-02-18T20:48:12.994+0000] {logging_mixin.py:188} INFO - [2024-02-18T20:48:12.993+0000] {dag.py:3823} INFO - Setting next_dagrun for csv_to_sqlserver_dag to None, run_after=None
[2024-02-18T20:48:15.716+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/ETL_LichtBlick.py took 7.370 seconds
[2024-02-18T20:48:46.283+0000] {processor.py:161} INFO - Started process (PID=4208) to work on /opt/airflow/dags/ETL_LichtBlick.py
[2024-02-18T20:48:46.285+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/ETL_LichtBlick.py for tasks to queue
[2024-02-18T20:48:46.287+0000] {logging_mixin.py:188} INFO - [2024-02-18T20:48:46.287+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/ETL_LichtBlick.py
[2024-02-18T20:48:47.440+0000] {logging_mixin.py:188} INFO - [2024-02-18T20:48:47.437+0000] {templater.py:95} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/template/templater.py", line 93, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/airflow/.local/lib/python3.8/site-packages/jinja2/loaders.py", line 204, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: ./dags/script/Dim.sql
[2024-02-18T20:48:47.444+0000] {logging_mixin.py:188} INFO - [2024-02-18T20:48:47.443+0000] {templater.py:95} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/template/templater.py", line 93, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/airflow/.local/lib/python3.8/site-packages/jinja2/loaders.py", line 204, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: ./dags/script/Dim.sql
[2024-02-18T20:48:47.450+0000] {processor.py:840} INFO - DAG(s) 'csv_to_sqlserver_dag' retrieved from /opt/airflow/dags/ETL_LichtBlick.py
[2024-02-18T20:48:47.520+0000] {logging_mixin.py:188} INFO - [2024-02-18T20:48:47.519+0000] {dag.py:3036} INFO - Sync 1 DAGs
[2024-02-18T20:48:47.545+0000] {logging_mixin.py:188} INFO - [2024-02-18T20:48:47.544+0000] {dag.py:3823} INFO - Setting next_dagrun for csv_to_sqlserver_dag to None, run_after=None
[2024-02-18T20:48:47.585+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/ETL_LichtBlick.py took 1.309 seconds
